version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resto_API
    volumes:
      - ./frontend/build:/app/frontend/build
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SERVER_PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - mysql_db
      - frontend
    networks:
      - resto_network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resto_ui
    networks:
      - resto_network
    ports:
      - "3000:3000"

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      - resto_network

networks:
  resto_network:
    name: resto_network
    driver: bridge

volumes:
  db_data:
    name: resto_db_data